module.exports = {
    FETCH_ORDERS_REQUESTED              : 'FETCH_ORDERS_REQUESTED',
    FETCH_ORDERS_SUCCEED                : 'FETCH_ORDERS_SUCCEED',
    FETCH_ORDERS_FAILED                 : 'FETCH_ORDERS_FAILED',
    FETCH_PRODUCTS_REQUESTED            : 'FETCH_PRODUCTS_REQUESTED',
    FETCH_PRODUCTS_SUCCEED              : 'FETCH_PRODUCTS_SUCCEED',    
    FETCH_PRODUCTS_FAILED               : 'FETCH_PRODUCTS_FAILED',
    FETCH_EXPENSES_REQUESTED            : 'FETCH_EXPENSES_REQUESTED',
    FETCH_EXPENSES_SUCCEED              : 'FETCH_EXPENSES_SUCCEED',
    FETCH_EXPENSES_FAILED               : 'FETCH_EXPENSES_FAILED',
    FETCH_INCOMES_REQUESTED             : 'FETCH_INCOMES_REQUESTED',
    FETCH_INCOMES_SUCCEED               : 'FETCH_INCOMES_SUCCEED',
    FETCH_INCOMES_FAILED                : 'FETCH_INCOMES_FAILED',
    FETCH_CATEGORIES_REQUESTED          : 'FETCH_CATEGORIES_REQUESTED',
    FETCH_CATEGORIES_SUCCEED            : 'FETCH_CATEGORIES_SUCCEED',
    FETCH_CATEGORIES_FAILED             : 'FETCH_CATEGORIES_FAILED'
}
