export const FETCH_SALES        = 'FETCH_SALES';
export const FETCH_SALES_ERROR  = 'FETCH_SALES_ERROR';
export const FETCH_PRODUCTS        = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_ERROR  = 'FETCH_PRODUCTS_ERROR';
