module.exports = {
    FETCH_SALES            : 'FETCH_SALES',
    FETCH_SALES_ERROR      : 'FETCH_SALES_ERROR',
    FETCH_PRODUCTS         : 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_ERROR   : 'FETCH_PRODUCTS_ERROR',
    FETCH_EXPENSES         : 'FETCH_EXPENSES',
    FETCH_EXPENSES_ERROR   : 'FETCH_EXPENSES_ERROR',
    FETCH_INCOMES          : 'FETCH_INCOMES',
    FETCH_INCOMES_ERROR    : 'FETCH_INCOMES_ERROR',
    FETCH_CATEGORIES       : 'FETCH_CATEGORIES',
    FETCH_CATEGORIES_ERROR : 'FETCH_CATEGORIES_ERROR'
}
